### ISSUE TITLE
Cleanup du repo

### ISSUE THREAD

**Issue by DragonJoker** [LaurentDuroisin/ODFAEG#1]
En l'état, il est très sale pour plusieurs raisons:
- Les fichiers temporaires de l'éditeur (*.*~) sont dans le repo
- Les fichiers résultat de compilation (*.o) sont dans le repo
- Les fichiers binaires (les exécutables) sont dans le repo
- Il y a duplication de dossier : un sous-dossier ODFAEG dans le repo, qui contient la même chose que la racine (aux modifications de fichiers près).

**Comment by DragonJoker** [comment]
J'ai de mon côté clean les 2 premiers points, par contre pour le dernier que faudrait-il faire ?
- Supprimer le sous dossier ODFAEG ?
- Ou supprimer les doublons dans la racine ?

**Comment by DragonJoker** [comment]
Et pour les exécutables, à mon sens ils n'ont rien à faire dans le repo, sachant qu'ils sont censés être regénérables depuis les sources

**Comment by LaurentDuroisin** [comment]
J'ai supprimé les doublons dans la racine.

**Comment by DragonJoker** [comment]
Il reste encore des doublons :
- le dossier Demos (et celui à la racine contient deux dossiers ODFAEG-CLIENT)
- le dossier clfiles
- le dossier cmake
- le dossier doxygen
- le dossier extlibs
- le dossier Shaders
- le dossier tools
- le fichier CMakeLists.txt
- le fichier license.txt
- le fichier readme.txt

**Comment by Ornito** [comment]
Doublons supprimés

**Comment by sfhacker** [comment]
Again for a second time, please use English as much as possible.
