### ISSUE TITLE
Libs externes

### ISSUE THREAD

**Issue by DragonJoker** [LaurentDuroisin/ODFAEG#2]
Tu ne devrais pas fournir celles-ci, mais permettre à l'utilisateur de sélectionner celles qu'il a sur son système (ou celles qu'il a compilées), c'est une des utilités de CMake.

**Comment by Ornito** [comment]
Tu as raison mais une vraie galère pour les recompiler sous windows donc je les met dans la sauvegarde.

**Comment by sfhacker** [comment]
Again, please use English as much as possible!
